# Generated by Django 2.2.3 on 2022-03-04 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': '2. Hodimlarning kurslar bazasi'},
        ),
    ]
