# Generated by Django 2.2.3 on 2022-03-11 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_auto_20220310_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstaff',
            name='coursen',
        ),
    ]
