# Generated by Django 2.2.3 on 2022-03-11 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_remove_userstaff_coursen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Createcourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(verbose_name='Kursingiz haqida batafsil yozing')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='course/')),
                ('coursen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.Course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Userstaff')),
            ],
            options={
                'verbose_name': '3. Kurslar bazasi',
            },
        ),
    ]
