# Generated by Django 2.2.3 on 2022-03-12 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_auto_20220312_0354'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstaff',
            name='about',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="O'qtuvchi bilish doirasi"),
        ),
    ]
