# Generated by Django 2.2.3 on 2022-03-12 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0008_createlesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='createcourse',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Sarlavha matni'),
        ),
    ]
