# Generated by Django 2.2.3 on 2022-03-31 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0011_auto_20220318_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='createcourse',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='createlesson',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
