# Generated by Django 2.2.3 on 2022-03-04 00:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('moderator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userstudent',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('sex', models.CharField(blank=True, choices=[('ERKAK', 'ERKAK'), ('AYOL', 'AYOL')], max_length=100, null=True, verbose_name='Jinsi')),
                ('phone_number', models.CharField(blank=True, max_length=17, null=True, verbose_name='telefon nomer')),
                ('student_image', models.ImageField(blank=True, null=True, upload_to='student_images')),
            ],
            options={
                'verbose_name': '1. Talabalar bazasi',
            },
        ),
    ]
