# Generated by Django 2.2.3 on 2022-03-10 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderator', '0002_usermoderator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermoderator',
            options={'verbose_name': '2. Moderatorlar bazasi'},
        ),
        migrations.AlterField(
            model_name='usermoderator',
            name='staff_image',
            field=models.ImageField(blank=True, null=True, upload_to='moderator/'),
        ),
    ]
