# Generated by Django 2.2.3 on 2022-03-18 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderator', '0003_auto_20220310_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermoderator',
            name='sex',
            field=models.CharField(blank=True, choices=[('Erkak', 'Erkak'), ('Ayol', 'Ayol')], max_length=100, null=True, verbose_name='Jinsi'),
        ),
    ]
