# Generated by Django 2.2.3 on 2022-03-19 11:17

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderator', '0004_auto_20220318_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('description', models.TextField(verbose_name='Qisqacha malumot')),
                ('text', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': '4. Maqolalar',
            },
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('description', models.TextField(verbose_name='Qisqacha malumot')),
                ('text', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': '3. Topshiriqlar',
            },
        ),
        migrations.CreateModel(
            name='Write',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('description', models.TextField(verbose_name='Qisqacha malumot')),
                ('text', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': '5. Eng yaxshi dasturlarni yozish',
            },
        ),
    ]
