# Generated by Django 2.2.3 on 2022-03-19 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderator', '0005_articles_tasks_write'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='articles/'),
        ),
        migrations.AddField(
            model_name='tasks',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tasks/'),
        ),
        migrations.AddField(
            model_name='write',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='write/'),
        ),
    ]
