# Generated by Django 2.2.3 on 2022-03-19 20:14

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('moderator', '0006_auto_20220319_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='pub_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasks',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2022, 3, 19, 20, 14, 25, 979366, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='write',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2022, 3, 19, 20, 14, 30, 896882, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
