# Generated by Django 2.2.3 on 2022-04-20 17:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('moderator', '0009_teacher_application'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher_application',
            options={'verbose_name': '5. Kurs ochish arizasi'},
        ),
        migrations.AddField(
            model_name='teacher_application',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='teacher_application',
            name='upload',
            field=models.FileField(default=datetime.datetime(2022, 4, 20, 17, 22, 23, 849334, tzinfo=utc), upload_to='cv/'),
            preserve_default=False,
        ),
    ]
