# Generated by Django 2.2.3 on 2022-04-20 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderator', '0010_auto_20220420_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_application',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='cv/'),
        ),
    ]
