# Generated by Django 2.2.3 on 2022-04-21 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moderator', '0012_teacher_application_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher_application',
            name='phone',
        ),
    ]
