# Generated by Django 2.2.3 on 2022-04-21 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderator', '0013_remove_teacher_application_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_application',
            name='phone_number',
            field=models.CharField(max_length=30, verbose_name='Tel nomber'),
        ),
    ]
